#!/usr/bin/env python3
"""gen_app_agent.py — regenerate app_agent.md from graphify-out/graph.json.

Generic: works on ANY project graphify has indexed. No project-specific content —
it derives the module map and hub functions purely from the graph. Fast, no LLM.

Run manually:  python3 scripts/gen_app_agent.py [PROJECT_DIR]
Wired into:    the post-commit hook installed by scripts/install-hooks.sh

PROJECT_DIR defaults to the parent of this script's repo, or $PI_DIR, or cwd.
"""
import json
import os
import sys
from pathlib import Path
from collections import defaultdict


def project_root():
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).resolve()
    if os.environ.get("PI_DIR"):
        return Path(os.environ["PI_DIR"]).resolve()
    return Path.cwd()


def main():
    root = project_root()
    graph = root / "graphify-out" / "graph.json"
    labels_f = root / "graphify-out" / ".graphify_labels.json"
    out = root / "app_agent.md"

    if not graph.exists():
        print(f"[gen_app_agent] no graph at {graph} — run /graphify first; skipping", file=sys.stderr)
        return 0

    g = json.loads(graph.read_text(encoding="utf-8"))
    nodes = g.get("nodes", [])
    links = g.get("links", g.get("edges", []))
    labels = json.loads(labels_f.read_text(encoding="utf-8")) if labels_f.exists() else {}

    comm = defaultdict(list)
    for n in nodes:
        comm[str(n.get("community", "?"))].append(n)

    deg = defaultdict(int)
    def nid(x): return x.get("id") if isinstance(x, dict) else x
    for l in links:
        deg[nid(l.get("source"))] += 1
        deg[nid(l.get("target"))] += 1

    funcs = [n for n in nodes if n.get("label", "").endswith("()")]
    gods = sorted(funcs, key=lambda n: -deg.get(n["id"], 0))[:12]

    def dom_file(ns):
        files = defaultdict(int)
        for n in ns:
            sf = n.get("source_file") or ""
            if sf:
                files[sf] += 1
        return max(files, key=files.get) if files else "?"

    sized = sorted(comm.items(), key=lambda kv: -len(kv[1]))

    L = []
    L.append("# app_agent.md — codebase map for the pi agent")
    L.append("")
    L.append("> Auto-generated from the graphify knowledge graph (`graphify-out/graph.json`).")
    L.append(f"> {len(nodes)} nodes · {len(links)} edges · {len(comm)} modules. "
             "Regenerated by the post-commit hook on code changes.")
    L.append(">")
    L.append("> **Purpose:** locate the right file/function before reading it. Pair with `AGENTS.md` (behaviour rules).")
    L.append("")
    L.append("> ⚠️ **Do NOT blind-read large files just to orient.** Use the tables below to jump")
    L.append("> straight to the one or two files a task actually needs. The map costs ~2k tokens;")
    L.append("> blind-reading core files to learn structure can cost 100k+. Open a file only once")
    L.append("> this map tells you it's the right one.")
    L.append("")
    L.append("## Core abstractions (most-connected functions)")
    L.append("These are the hubs — touch them and you touch much of the system.")
    L.append("")
    L.append("| Function | File | Edges |")
    L.append("|---|---|---|")
    for n in gods:
        sf = n.get("source_file", "?")
        loc = ":" + n["source_location"][1:] if n.get("source_location") else ""
        L.append(f"| `{n['label']}` | [{sf}]({sf}){loc} | {deg.get(n['id'], 0)} |")
    L.append("")
    L.append("## Modules (communities) — where things live")
    L.append("Ranked by size. Each row: the module's job and its primary file.")
    L.append("")
    L.append("| Module | Primary file | Nodes |")
    L.append("|---|---|---|")
    for cid, ns in sized:
        if len(ns) < 5:
            continue
        lbl = labels.get(cid, "Community " + cid)
        df = dom_file(ns)
        df = df.split("/")[-1] if df.startswith("/") else df
        L.append(f"| {lbl} | [{df}]({df}) | {len(ns)} |")
    L.append("")

    out.write_text("\n".join(L), encoding="utf-8")
    print(f"[gen_app_agent] wrote {out} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never block a commit hook
        print(f"[gen_app_agent] failed: {exc}", file=sys.stderr)
        sys.exit(0)
